library(ggmap)
library(ggplot2)
eu.data <- read.csv('/home/boris/Work/poetic/geo/prepared_data/cities_all_log.csv')
eu <- get_map(location = 'europe', zoom=4, maptype="roadmap", color='bw', language='en-US')
eu.map <- ggmap(eu)
eu.map.o <- eu.map + geom_point(data = eu.data, aes(x = lon, y = lat, color = Freq, size = Freq))
eu.map.o <- eu.map.o + scale_color_gradient(low = 'brown', high = 'yellow')
eu.map.o <- eu.map.o + ggtitle('Frequency of city names in Russian poetry\n') + theme(legend.position = 'right')
print(eu.map.o)
ggsave('/home/boris/Work/poetic/geo/maps/euromap_all_log2.png', width=8, height=8)
dev.off()